config_ignore.settings:
  type: config_object
  label: 'Config Ignore Settings'
  mapping:
    settings_to_ignore:
      type: sequence
      label: 'List of ignored configurations'
      sequence:
        type: string